Repository falcosecurity/test-infra, pull requests merged in 2019-06, with the labels that each got.

#2 new: approve, lgtm, size, etc.
  prow/config/plugins.yaml
Labels: approved, lgtm, size/M

#3 new: add wip and dco plugins
  prow/config/plugins.yaml
Labels: approved, lgtm, size/XS

#10 new: add lifecycle and avoid auto assign
  prow/config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#13 new: enable hold plugin
  prow/config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#18 new: automatic branch cleaning
  prow/config/plugins.yaml
Labels: dco-signoff: yes, size/XS

#24 branch protections
  prow/cluster/branchprotector.yaml
  prow/cluster/deck.yaml
  prow/cluster/needs-rebase.yaml
  prow/config/configs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#29 Fix indentation of missing comment sections
  prow/config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#31 Branch protections for Falco
  prow/config/configs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#33 fix: work in progress label
  prow/config/configs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#34 fix: config updater config path
  prow/config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#35 Others branch protections
  prow/config/configs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#37 fix: disable approving review count for now
  prow/config/configs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#41 enable branch protection mandatory checks
  prow/config/configs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#44 new: specify status checks for branch protection
  prow/Makefile
  prow/cluster/branchprotector.yaml
  prow/cluster/configs.yaml
  prow/cluster/deck.yaml
  prow/cluster/hook.yaml
  prow/cluster/horologium.yaml
  prow/cluster/plank.yaml
  prow/cluster/sinker.yaml
  prow/cluster/tide.yaml
  prow/config/configs.yaml
  prow/config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#45 new: update tide
  prow/cluster/tide.yaml
  prow/config/configs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#46 update: change the self approval flag since the old one was deprecated
  prow/config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS
