Repository falcosecurity/test-infra, pull requests merged in 2020-12, with the labels that each got.

#233 update(config): increase timeout for prowjobs
  config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#235 falcosidekick: add required ci checks
  config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#240 prow: add required github status for charts repo
  config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#243 Pin Terraform v0.13.5 in CI/CD pipeline
  tools/deploy_terraform.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#244 Always run prow config check
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#245 Switch update-jobs to postsubmit now that check-config works for PR
  config/jobs/update-jobs/update-jobs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#249 Upping timeout and closing issue #228
  config/config.yaml
  images/build-drivers/build-drivers.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#255 Bump prow from v20201124-061f85d859 to v20201211-de9ccc9ff1
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/plank.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#257 update(config): set protected branch for the versioned website
  config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#258 fix(driverkit): check if publish folder needs to be synced
  driverkit/Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#253 Adding readme change to kickoff jobs
  driverkit/Makefile
  driverkit/README.md
  images/autobump/autobump.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#259 adding in jobs and script to build images for prowjobs
  config/jobs/build-prow-images/build-images.yaml
  images/publish.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#261 fixing build images errors
  images/publish.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#264 Bump prow from v20201211-de9ccc9ff1 to v20201217-2de500de27
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/plank.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#269 Remove old CircleCI jobs
  .circleci/config.yml
Labels: approved, dco-signoff: yes, lgtm, size/L
