Repository falcosecurity/test-infra, pull requests merged in 2020-09, with the labels that each got.

#170 fix drivers cleanup (needs make)
  .circleci/config.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#171 musl (statically-linked) build job mandatory for Falco
  prow/config/configs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#173 new: prebuilt module for ubuntu-aws 5.4.0-1024-aws_24
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1024-aws_24.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1024-aws_24.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#178 update(driverkit/config): new ubuntu prebuilt drivers
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1025-aws_25.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.8.0-1005-aws_5.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.8.0-19-generic_20.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1025-aws_25.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.8.0-1005-aws_5.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.8.0-19-generic_20.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#177 adding prow propsal .... new PR with signoff
  proposals/20200915-prow.md
Labels: approved, dco-signoff: yes, lgtm, retest-not-required-docs-only, size/M

#180 update(driverkit/config): drivers updated to September 18th 2020
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.15.0-1081-aws_85.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1023-aws_23.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_4.15.0-116-generic_117.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.4.0-46-generic_50.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.15.0-1081-aws_85.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1023-aws_23.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_4.15.0-116-generic_117.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.4.0-46-generic_50.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#181 update(driverkit/config): bump drivers to September 23rd 2020
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.19.0-11-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.8.0-2-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.15.0-1084-aws_88.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.4.0-1115-aws_128.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1026-aws_26.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_4.15.0-119-generic_120.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_4.4.0-191-generic_221.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.4.0-49-generic_53.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.19.0-11-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.8.0-2-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.15.0-1084-aws_88.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.4.0-1115-aws_128.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1026-aws_26.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_4.15.0-119-generic_120.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_4.4.0-191-generic_221.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.4.0-49-generic_53.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#182 update(driverkit/config): drivers bump to september 24th 2020
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.8.0-20-generic_21.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.8.0-20-generic_21.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S
