Repository falcosecurity/test-infra, pull requests merged in 2020-11, with the labels that each got.

#203 Protect Falco hotfix release branch (0.26.2)
  prow/config/configs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#209 lifecycle bot
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#211 fix YAML indentation for periodic-rotten ProwJob
  config/jobs/lifecycle-bot/periodic-rotten.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#210 Add build-drivers jobs for all distros
  config/jobs/build-drivers/build-drivers.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#216 Fix drivers build jobs triggers
  config/jobs/build-drivers/build-drivers.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#226 Add https redirect to deck
  config/prow/deck.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#227 Increase default job timeout from 3h to 6h
  config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#231 Bump prow from v20201102-45eeca6478 to v20201124-061f85d859
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/plank.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M
