Repository falcosecurity/test-infra, pull requests merged in 2020-10, with the labels that each got.

#187 update(driverkit/config): bump drivers to September 30th 2020
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_4.19.0-0.bpo.6-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_4.19.0-0.bpo.8-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_4.19.0-0.bpo.9-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_4.19.0-10-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_4.19.0-11-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_4.19.0-6-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_4.19.0-8-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_4.19.0-9-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_5.4.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_5.4.0-0.bpo.3-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_5.4.0-0.bpo.4-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_5.5.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_5.6.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_5.7.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_5.8.0-0.bpo.2-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_5.8.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_5.8.0-2-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_4.4.0-1116-aws_129.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_4.4.0-192-generic_222.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.19.0-0.bpo.6-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.19.0-0.bpo.8-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.19.0-0.bpo.9-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.19.0-10-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.19.0-11-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.19.0-6-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.19.0-8-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.19.0-9-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.4.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.4.0-0.bpo.3-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.4.0-0.bpo.4-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.5.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.6.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.7.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.8.0-0.bpo.2-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.8.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.8.0-2-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.4.0-1116-aws_129.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_4.4.0-192-generic_222.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.19.0-0.bpo.6-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.19.0-0.bpo.8-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.19.0-0.bpo.9-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.19.0-10-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.19.0-11-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.19.0-6-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.19.0-8-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.19.0-9-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.4.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.4.0-0.bpo.3-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.4.0-0.bpo.4-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.5.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.6.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.7.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.8.0-0.bpo.2-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.8.0-0.bpo.2-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.8.0-2-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.4.0-1116-aws_129.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_4.4.0-192-generic_222.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#189 update(OWNERS): adding jonahjon and maxgio92
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, retest-not-required-docs-only, size/XS

#194 docs: add docs for 1password
  docs/one-password.md
Labels: approved, dco-signoff: yes, lgtm, retest-not-required-docs-only, size/S

#199 chore: small improvements to deploy script
  deploy.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#183 Proposal for Falco Infra Admins
  proposals/20200925-admins.md
Labels: approved, dco-signoff: yes, lgtm, retest-not-required-docs-only, size/S

#202 update(driverkit/config): bump drivers to October 30th
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_4.14.200-155.322.amzn2.x86_64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux_4.14.200-116.320.amzn1.x86_64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_4.9.0-14-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_4.14.200-155.322.amzn2.x86_64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux_4.14.200-116.320.amzn1.x86_64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.9.0-14-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_4.14.200-155.322.amzn2.x86_64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux_4.14.200-116.320.amzn1.x86_64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.9.0-14-amd64_1.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M
