Repository falcosecurity/test-infra, pull requests merged in 2021-05, with the labels that each got.

#382 Update driver configurations (2021-05-02)
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/centos_3.10.0-1160.25.1.el7.x86_64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_4.15.0-1100-aws_107.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_4.15.0-1101-aws_108.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.4.0-1046-aws_48.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.4.0-1047-aws_49.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.8.0-1031-aws_33.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_3.10.0-1160.25.1.el7.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_4.15.0-1100-aws_107.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_4.15.0-1101-aws_108.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.4.0-1046-aws_48.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.4.0-1047-aws_49.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.8.0-1031-aws_33.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/centos_3.10.0-1160.25.1.el7.x86_64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.15.0-1100-aws_107.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.15.0-1101-aws_108.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1046-aws_48.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1047-aws_49.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.8.0-1031-aws_33.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/centos_3.10.0-1160.25.1.el7.x86_64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.15.0-1100-aws_107.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.15.0-1101-aws_108.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1046-aws_48.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1047-aws_49.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.8.0-1031-aws_33.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#383 fix(config/clusters/storage.tf): s3 bucket lifecycle aws provider syntax
  config/clusters/storage.tf
Labels: approved, dco-signoff: yes, lgtm, size/S

#384 fix(config/clusters/storage.tf): s3 bucket lifecycle aws provider syntax
  config/clusters/storage.tf
Labels: approved, dco-signoff: yes, lgtm, size/XS

#385 fix(config/prow/deck.yaml): add required cookie secret path flag
  config/prow/deck.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#386 fix(tools/deploy_prow.sh): fix pr-status secrets key
  tools/deploy_prow.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#387 Add new AmazonLinux2 EKS AMI kernel
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.110-54.182.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.110-54.182.amzn2.x86_64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_5.4.110-54.182.amzn2.x86_64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_5.4.110-54.182.amzn2.x86_64_1.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#394 fix(images/docker-dind/Dockerfile): upgrade awscli to v2 according to usage
  images/docker-dind/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#399 amazonlinux2_5.4.110-54.189 config
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.110-54.189.amzn2.x86_64_1.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#397 prow bump fix, removing plank
  config/prow/plank.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#402 Add metrics-server to collect resource metrics from test containers
  tools/deploy_prow.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#403 Bump prow from v20210409-7d5e552c49 to v20210521-0713522bd8
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M
