Repository falcosecurity/test-infra, pull requests merged in 2021-12, with the labels that each got.

#573 add falco ko amazon linux2 2_5.4.117-58.216
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#572 Add kernel module for amazonlinux2_5.4.156-83.273
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.156-83.273.amzn2.x86_64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.4.156-83.273.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.156-83.273.amzn2.x86_64_1.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#570 Bump prow from v20211119-1147d04f59 to v20211126-48cb2fc883
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#574 Add kernel Ubuntu-generic 4.15.0-159_167
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_4.15.0-159-generic_167.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/ubuntu-generic_4.15.0-159-generic_167.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_4.15.0-159-generic_167.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S, ok-to-test

#577 Add amazonlinux2_4.14.252-195.483 kernel support
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S, ok-to-test

#579 Bump prow from v20211203-281e29a97a to v20211210-dfd4c4dd7d
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#578 Create ubuntu-aws_5.4.0-1060-aws_63
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-aws_5.4.0-1060-aws_63.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/ubuntu-aws_5.4.0-1060-aws_63.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.4.0-1060-aws_63.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S, ok-to-test
