Repository falcosecurity/test-infra, pull requests merged in 2021-11, with the labels that each got.

#552 Create debian_5.10.0-9
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/debian_5.10.0-9-amd64_1.yaml
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/debian_5.10.0-9-cloud-amd64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/debian_5.10.0-9-amd64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/debian_5.10.0-9-cloud-amd64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/debian_5.10.0-9-amd64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/debian_5.10.0-9-cloud-amd64_1.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes, ok-to-test

#553 update: add automake dep to build-libs dockerfile
  images/build-libs/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#555 update(build-libs): test minimal libs build
  config/jobs/build-libs/build-libs.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S, ok-to-test

#556 feat(driverkit/config): support ubuntu-generic_5.4.0-90-generic_101
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.4.0-90-generic_101.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/ubuntu-generic_5.4.0-90-generic_101.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.4.0-90-generic_101.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#544 Add eBPF probe support for CentOS 5.4.0-80.90.2.el7.x86_64
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/centos_5.4.0-80.90.2.el7.x86_64_1.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#554 ci(tools/deploy_terraform.sh): use terraform required version
  tools/deploy_terraform.sh
Labels: size/M, lgtm, approved, dco-signoff: yes

#541 Bump prow from v20211008-8c358bcb9d to v20211111-bce61c7c4a
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#557 Adding ebpf support for AmazonLinux 2 5.4.149-73.259
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.149-73.259.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.149-73.259.amzn2.x86_64_1.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, needs-ok-to-test

#558 Bump prow from v20211111-bce61c7c4a to v20211119-1147d04f59
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#562 fix(config/jobs): add pod utils to arm-build jobs
  config/jobs/arm-build/arm-build.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#561 fix(config): katacoda-scenarios does not use `do-not-merge/release-note-label-needed label` label
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#565 update(images): upgrade base image to golang:1.17
  images/autobump/Dockerfile
  images/update-falco-k8s-manifests/Dockerfile
  images/update-maintainers/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#559 Poiana wants to update its new GPG key's fingerprint
  config/jobs/autobump/autobump.yaml
  images/autobump/autobump.sh
  images/update-falco-k8s-manifests/entrypoint.sh
  images/update-maintainers/entrypoint.sh
Labels: lgtm, approved, dco-signoff: yes, size/S

#567 update(images/update-maintainers): auto-add jasondellaluce
  images/update-maintainers/persons.json
Labels: lgtm, approved, size/XS, dco-signoff: yes

#568 Update persons.json
  images/update-maintainers/persons.json
Labels: lgtm, approved, size/XS, dco-signoff: yes

#566 chore(images/update-maintainers/persons.json): update maxgio92 company
  images/update-maintainers/persons.json
Labels: lgtm, approved, size/XS, dco-signoff: yes
