Repository falcosecurity/test-infra, pull requests merged in 2021-08, with the labels that each got.

#477 Bump prow from v20210723-55eee17612 to v20210730-5757a5d200
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#484 Bump prow from v20210730-5757a5d200 to v20210806-c95403cd67
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#483 updating cluster autoscaler
  config/prow/cluster-autoscaler.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#480 Add slightly older (but still extant) AMI kernel version: 5.4.91-41.139.amzn2.x86_64
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.91-41.139.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.91-41.139.amzn2.x86_64_1.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S, ok-to-test

#482 fixing prow lifecycle bot
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#487 ci: prevent critical resources from destroy
  config/distribution/containers.tf
  config/distribution/distribution.tf
Labels: lgtm, approved, dco-signoff: yes, size/S

#488 Make ARM EKS Node Group scaling config customizable
  config/clusters/TERRAFORM.md
  config/clusters/eks.tf
  config/clusters/eks_variables.tf
Labels: lgtm, approved, dco-signoff: yes, size/S

#489 Bump prow from v20210806-c95403cd67 to v20210813-c9ba83f08c
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#494 Add 5.4.95-42.163.amzn2.x86_64 to 17f5df52a7d9ed6bb12d3b1768460def84
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.95-42.163.amzn2.x86_64_1.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, needs-ok-to-test

#493 creating signed PR for #479 to add EKS AMI support
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#495 Update driver configurations (2021-08-22)
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.95-42.163.amzn2.x86_64_1.yaml
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-aws_5.11.0-1017-aws_18.yaml
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_4.15.0-156-generic_163.yaml
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.11.0-33-generic_35.yaml
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.4.0-83-generic_93.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.11.0-1017-aws_18.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_4.15.0-156-generic_163.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.11.0-33-generic_35.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.4.0-83-generic_93.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.11.0-1017-aws_18.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_4.15.0-156-generic_163.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.11.0-33-generic_35.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.4.0-83-generic_93.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.11.0-1017-aws_18.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_4.15.0-156-generic_163.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.11.0-33-generic_35.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.4.0-83-generic_93.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.11.0-1017-aws_18.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_4.15.0-156-generic_163.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.11.0-33-generic_35.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.4.0-83-generic_93.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L

#501 Bump prow from v20210818-b81cb0bc7b to v20210827-98f54bde95
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes
