Repository falcosecurity/test-infra, pull requests merged in 2021-06, with the labels that each got.

#413 Bump prow from v20210521-0713522bd8 to v20210526-84965e233e
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#418 Unblocking CI attempt by adhering to Rego.
  config/clusters/storage.tf
Labels: approved, dco-signoff: yes, lgtm, size/XS

#420 Bump prow from v20210526-84965e233e to v20210604-95cc9f4b68
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#426 terrascan fix
  .circleci/config.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#416 Add support for v20210526 Amazon EKS AMIs
  driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/S

#427 tweaking lgtm to reduce test-retriggering
  config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#429 Bump prow from v20210604-95cc9f4b68 to v20210609-402d3ba6b7
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#431 fixing issue for join url
  config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#428 Update driver configurations (2021-06-12)
  driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
  driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/centos_3.10.0-1160.31.1.el7.x86_64_1.yaml
  driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/debian_4.19.0-17-amd64_1.yaml
  driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/debian_4.19.0-17-cloud-amd64_1.yaml
  driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/debian_5.10.0-0.bpo.7-amd64_1.yaml
  driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/debian_5.10.0-0.bpo.7-cloud-amd64_1.yaml
  driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/ubuntu-aws_5.11.0-1009-aws_1.yaml
  driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/ubuntu-aws_5.11.0-1009-aws_9.yaml
  driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/ubuntu-aws_5.8.0-1036-aws_38.yaml
  driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/ubuntu-generic_5.11.0-20-generic_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/centos_3.10.0-1160.31.1.el7.x86_64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_4.19.0-17-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_4.19.0-17-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_5.10.0-0.bpo.7-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_5.10.0-0.bpo.7-cloud-amd64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.11.0-1009-aws_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.11.0-1009-aws_9.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.8.0-1036-aws_38.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.11.0-20-generic_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_3.10.0-1160.31.1.el7.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/debian_4.19.0-17-amd64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/debian_4.19.0-17-cloud-amd64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/debian_5.10.0-0.bpo.7-amd64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/debian_5.10.0-0.bpo.7-cloud-amd64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.11.0-1009-aws_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.11.0-1009-aws_9.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.8.0-1036-aws_38.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.11.0-20-generic_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/centos_3.10.0-1160.31.1.el7.x86_64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.19.0-17-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.19.0-17-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.10.0-0.bpo.7-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.10.0-0.bpo.7-cloud-amd64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.11.0-1009-aws_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.11.0-1009-aws_9.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.8.0-1036-aws_38.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.11.0-20-generic_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/centos_3.10.0-1160.31.1.el7.x86_64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.19.0-17-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.19.0-17-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.10.0-0.bpo.7-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.10.0-0.bpo.7-cloud-amd64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.11.0-1009-aws_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.11.0-1009-aws_9.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.8.0-1036-aws_38.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.11.0-20-generic_1.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#433 fixing terrascan, and tightning SG rules
  .circleci/config.yml
  config/clusters/security_groups.tf
Labels: approved, dco-signoff: yes, lgtm, size/XS

#438 updating TF version CI broken
  config/clusters/TERRAFORM.md
  config/clusters/terraform_versions.tf
  tools/deploy_terraform.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#443 feat: downgrade prow k8s from 1.20 to 1.18
  config/clusters/eks.tf
Labels: approved, dco-signoff: yes, lgtm, size/XS

#442 test: set prow-eks-upgrade ghissue job to run monday morning
  config/jobs/recurring-ghissues/prow-eks-upgrade.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#444 Bump prow from v20210609-402d3ba6b7 to v20210617-4b498df7d4
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#446 update(config): protect branch v0.28 of the falco-website
  config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#445 Update driver configurations (2021-06-22)
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.4.0-76-generic_85.yaml
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.8.0-57-generic_64.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.4.0-76-generic_85.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.8.0-57-generic_64.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.4.0-76-generic_85.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.8.0-57-generic_64.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.4.0-76-generic_85.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.8.0-57-generic_64.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.4.0-76-generic_85.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.8.0-57-generic_64.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#448 add support for centos_4.18.0-277
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-277.el8.x86_64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/centos_4.18.0-277.el8.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_4.18.0-277.el8.x86_64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/centos_4.18.0-277.el8.x86_64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/centos_4.18.0-277.el8.x86_64_1.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#453 Amazon Linux 2 5.4.117-58.216.amzn2.x86_64 support
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#454 docs: fixes typo in README
  README.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#455 Bump prow from v20210617-4b498df7d4 to v20210625-abd67550c2
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#456 Update eks 118
  config/clusters/eks.tf
Labels: approved, dco-signoff: yes, lgtm, size/XS

#457 updating control plan to 119
  config/clusters/eks.tf
Labels: approved, dco-signoff: yes, lgtm, size/XS

#458 updating nodegroups to 1.19
  config/clusters/eks.tf
Labels: approved, dco-signoff: yes, lgtm, size/XS
