Repository falcosecurity/test-infra, pull requests merged in 2021-02, with the labels that each got.

#299 fixing upstream flag change from pr-creator
  images/autobump/autobump.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#302 fixing rbac for update-jobs
  config/prow/update-jobs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#301 update(config): kilt doesn't use release note blocks
  config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#304 Bump prow from v20210108-eac8059329 to v20210205-451988f24f
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/plank.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#306 update(images/update-maintainers): add Frank's details (welcome!)
  images/update-maintainers/persons.json
Labels: approved, dco-signoff: yes, lgtm, size/XS

#307 update(config): initial `falcosidekick-ui` prow configuration
  config/config.yaml
  config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#308 Fix circleci jobs filtering
  .circleci/config.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#309 update(config): add required status check for falcosidekick-ui
  config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#310 update(test-infra/config): add target URL for tide
  config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#312 Bump prow from v20210205-451988f24f to v20210211-72696ce111
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/plank.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#315 Update driver configurations (2021-02-22)
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_4.14.219-161.340.amzn2.x86_64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux_4.14.219-119.340.amzn1.x86_64_1.yaml
  driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_4.4.0-1122-aws_136.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.219-161.340.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux_4.14.219-119.340.amzn1.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_4.4.0-1122-aws_136.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_4.14.219-161.340.amzn2.x86_64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux_4.14.219-119.340.amzn1.x86_64_1.yaml
  driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.4.0-1122-aws_136.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_4.14.219-161.340.amzn2.x86_64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux_4.14.219-119.340.amzn1.x86_64_1.yaml
  driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.4.0-1122-aws_136.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#321 update(config): add trigger plugin for falcosecurity/libs
  config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#322 fix(config/lobs/build-libs): do not skip PR against master
  config/jobs/build-libs/build-libs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#316 Bump prow from v20210211-72696ce111 to v20210218-445b85c368
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/plank.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#320 Add build-libs AWS ECR Repository
  tools/create_ecr.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#324 update(config/jobs/build-libs): add build job with no bundled deps
  config/jobs/build-libs/build-libs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S
