Repository falcosecurity/test-infra, pull requests merged in 2021-10, with the labels that each got.

#523 update(config): add protected branch for Falco website v0.29
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#521 Bump prow from v20210916-7657ce97bf to v20211001-6cf1ab3b20
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#549 Falco Amzn2 5.10.68-62.173 kernel module
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.10.68-62.173.amzn2.x86_64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.68-62.173.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.10.68-62.173.amzn2.x86_64_1.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S, ok-to-test
