Repository falcosecurity/test-infra, pull requests merged in 2022-12, with the labels that each got.

#915 chore(images): updated update-syscalls PR title.
  images/update-syscalls/entrypoint.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#918 allow an entry in driverkit FAQ about the drivers website
  driverkit/README.md
  driverkit/drivers_website_screenshot.png
Labels: lgtm, approved, size/XS, dco-signoff: yes

#922 update(config/org.yaml): add hbrueckner as member to lib-maintainers
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#923 fix(config): fixed driverkit required_status_check.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#920 vote: propose fededp as a test-infra maintainer
  OWNERS
Labels: lgtm, approved, size/XS, dco-signoff: yes

#927 chore(config): add fededp as test-infra-maintainers to org.
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#925 update(images): updated kernel-crawler image to latest tag.
  images/update-kernels/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#928 update(images): bump kernel-crawler to 0.5.0.
  images/update-kernels/Dockerfile
  images/update-kernels/entrypoint.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#924 Improve the driver configs contribution documentation
  README.md
  driverkit/README.md
Labels: size/M, lgtm, approved, dco-signoff: yes

#933 new(images): porting of dind for multiplatform
  images/docker-dind/Dockerfile
  images/docker-dind/Makefile
Labels: lgtm, approved, dco-signoff: yes, size/S, ok-to-test

#936 chore(images): fixed typo in dockerfile
  images/docker-dind/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#938 new(config): add falcosecurity/rules repository config
  config/config.yaml
  config/org.yaml
  config/plugins.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#913 Bump prow from v20221117-3815e13b72 to v20221220-5c7fbe528a
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes
