Repository falcosecurity/test-infra, pull requests merged in 2022-11, with the labels that each got.

#889 fix(images): fixed update-syscalls image deps.
  images/update-syscalls/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#887 set default driver for the website to the lastest release
  .vscode/settings.json
  images/update-drivers-website/index.html
Labels: lgtm, approved, size/XS, dco-signoff: yes

#891 chore(images): improved update-syscalls PR body to add an area and release notes, as requested by libs repo
  images/update-syscalls/entrypoint.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#886 update(images): bump kernel-crawler image version.
  images/update-kernels/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#888 Bump prow from v20221021-f6c02074bb to v20221028-a8625c1f93
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#890 add EXONER4TED as org member
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, needs-ok-to-test

#893 update(images): bumped kernel-crawler to latest bugfix.
  images/update-kernels/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#896 chore(images): moved syscalls-bumper under falcosecurity.
  images/update-syscalls/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#898 fix(config): add syscalls-bumper-maintainers section.
  config/org.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#899 Bump prow from v20221028-a8625c1f93 to v20221104-4497ace285
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#902 update(images): bumped kernel-crawler version to 0.4.2
  images/update-kernels/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#903 update(images): updated crawler to 0.4.3.
  images/update-kernels/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#905 update(images): updated kernel crawler to 0.4.4.
  images/update-kernels/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#904 Bump prow from v20221104-4497ace285 to v20221111-fe4f3e2158
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#906 update(images): bumped kernel-crawler to 0.4.5.
  images/update-kernels/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#909 Bump prow from v20221111-fe4f3e2158 to v20221117-3815e13b72
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#901 update(images): bumped update-syscalls image to latest syscalls bumper.
  images/update-syscalls/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#911 update(config): update protected branches for libs 0.9.2 / falco 0.33.1 release
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes
