Repository falcosecurity/test-infra, pull requests merged in 2022-01, with the labels that each got.

#580 Bump prow from v20211210-dfd4c4dd7d to v20211229-d20cd1c87e
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#587 update(images/update-maintainers): re-add jasondellaluce
  images/update-maintainers/persons.json
Labels: lgtm, approved, dco-signoff: yes

#591 update: persons.json
  images/update-maintainers/persons.json
Labels: lgtm, approved, size/XS, dco-signoff: yes

#588 Bump prow from v20211229-d20cd1c87e to v20220107-bf45c6e760
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#584 Add support for CentOS 8.5 configs
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-348.2.1.el8.x86_64_1.yaml
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-348.7.1.el8.x86_64_1.yaml
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-348.el8.x86_64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/centos_4.18.0-348.2.1.el8.x86_64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/centos_4.18.0-348.7.1.el8.x86_64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/centos_4.18.0-348.el8.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_4.18.0-348.2.1.el8.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_4.18.0-348.7.1.el8.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_4.18.0-348.el8.x86_64_1.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes, ok-to-test

#590 add amazonlinux2_4.14.252-195.483 and amazonlinux2_5.10.75-79.358
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.yaml
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.10.75-79.358.amzn2.x86_64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.75-79.358.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.10.75-79.358.amzn2.x86_64_1.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#592 update(persons): add fededp
  images/update-maintainers/persons.json
Labels: lgtm, approved, dco-signoff: yes

#594 fix issues when driverkit is missing
  driverkit/Makefile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#596 adding ecr login to Makefile for base image pull
  images/build-drivers/Makefile
Labels: size/M, lgtm, approved, dco-signoff: yes

#601 update: fix plugin name regex in build-plugins jobs
  config/jobs/build-plugins/build-plugins.yaml
  images/build-plugins/build-and-publish.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#593 Create debian_5.10.0-10
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/debian_5.10.0-10-amd64_1.yaml
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/debian_5.10.0-10-cloud-amd64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/debian_5.10.0-10-amd64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/debian_5.10.0-10-cloud-amd64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/debian_5.10.0-10-amd64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/debian_5.10.0-10-cloud-amd64_1.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes, ok-to-test

#598 Bump prow from v20220107-bf45c6e760 to v20220114-25626d8ef5
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: lgtm, approved, dco-signoff: yes

#605 fix(build-plugins): remove extra_refs from build-plugins-update-readme-postsubmit
  config/jobs/build-plugins/build-plugins.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#599 Adds amazonlinux2_5.4.162-86.275.amzn2.x86_64_1
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.162-86.275.amzn2.x86_64_1.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, needs-ok-to-test

#595 update driverkit
  images/build-drivers/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#602 Add 4.14.256-197.484.amzn2.x86_64 probe support
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#606 fix(script): correctly escapes newline character
  images/build-plugins/update-readme.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#608 Bump prow from v20220114-25626d8ef5 to v20220121-8b2d5086e4
  config/config.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/prow/branchprotector.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#611 Add support for new driver 5.4.162-86.275.amzn2.x86_64
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.4.162-86.275.amzn2.x86_64_1.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#614 Fix bash condition that prevented SKIP_EXISTING from actually being honored
  driverkit/utils/build
Labels: lgtm, approved, dco-signoff: yes, size/S

#615 Add amazonlinux2_4.14.246-187.474.amzn2.x86_64 BPF
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.246-187.474.amzn2.x86_64_1.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_4.14.246-187.474.amzn2.x86_64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_4.14.246-187.474.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.246-187.474.amzn2.x86_64_1.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#616 update(config): protect branch v0.30 for falco-website
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes
