Repository falcosecurity/test-infra, pull requests merged in 2022-08, with the labels that each got.

#787 fix(images): fixed deps for update-kernels image.
  images/update-kernels/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#788 update(config/org.yaml): add vjjmiras to org members
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#791 fix(config/plugins.yaml): enable maintainers team for milestone plugin
  config/plugins.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#782 Add support for minikube drivers
  driverkit/Makefile
  driverkit/utils/generate
  driverkit/utils/scrape_and_generate
Labels: size/M, lgtm, approved, dco-signoff: yes, needs-ok-to-test

#792 Bump prow from v20220721-cf42b99a12 to v20220727-38eaa13df1
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#790 chore: config for amazonlinux2_5.4.204-113.362
  driverkit/config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_5.4.204-113.362.amzn2.x86_64_1.yaml
  driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.4.204-113.362.amzn2.x86_64_1.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S, ok-to-test

#794 chore: add drivers support for kernel-5.10.0-0.bpo.15 x86_64
  driverkit/config/2.0.0+driver/x86_64/debian_5.10.0-0.bpo.15-amd64_1.yaml
  driverkit/config/39ae7d40496793cf3d3e7890c9bbdc202263836b/debian_5.10.0-0.bpo.15-amd64_1.yaml
  driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/debian_5.10.0-0.bpo.15-amd64_1.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S, ok-to-test

#796 feat(driverkit-kube): Build utils can now run on kube by DRIVERKIT_BACKEND variable
  driverkit/Makefile
  driverkit/utils/build
Labels: lgtm, approved, size/XS, dco-signoff: yes, needs-ok-to-test

#800 Bump prow from v20220727-38eaa13df1 to v20220805-e0ec00dd27
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#797 feat(driverkit-kube): Build utils can now run on kube
  driverkit/utils/build
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#799 update(config/plugins): disable release-note for falcoctl
  config/plugins.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#801 update(config.yaml): protect Falco `0.32.2` release branch
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#795 fix(utils-generate): Bringing back the compute functions
  driverkit/utils/generate
Labels: size/M, lgtm, approved, dco-signoff: yes, needs-ok-to-test

#802 adding amazonlinux2_5.4.204-113.362.amzn2
  driverkit/config/2.0.0+driver/x86_64/amazonlinux2_5.4.204-113.362.amzn2.x86_64_1.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#803 feat(driverkit-kube): Adding quote to DRIVERKIT_BACKEND
  driverkit/Makefile
  driverkit/utils/build
Labels: lgtm, approved, size/XS, dco-signoff: yes, needs-ok-to-test

#805 Bump prow from v20220805-e0ec00dd27 to v20220812-9414716697
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#808 cleanup(driverkit): remove a bintray reference + its script.
  driverkit/Makefile
  driverkit/utils/cleanup
Labels: size/M, lgtm, approved, dco-signoff: yes

#810 update(images/update-maintainers/persons.json): update `admiral0` affiliation
  images/update-maintainers/persons.json
Labels: lgtm, approved, size/XS, dco-signoff: yes

#815 update(config/org): add core-maintainers team
  config/org.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#806 update(images): bump driverkit version to 0.9.6
  images/build-drivers/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#816 update(config/org.yaml): add jasondellaluce to evolution-maintainers team
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#817 fix(config,driverkit,images): fix kernel-crawler -> test-infra dbg automation
  config/jobs/update-dbg/update-dbg.yaml
  driverkit/utils/scrape_and_generate
  images/update-kernels/entrypoint.sh
Labels: lgtm, approved, dco-signoff: yes, size/S

#821 Add missing trigger plugin to kernel-crawler
  config/plugins.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#820 update(config/plugins.yaml): kilt does not use release notes
  config/plugins.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#822 fix(config): make `kernels` branch of kernel-crawler protected.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes
