Repository falcosecurity/test-infra, pull requests merged in 2022-10, with the labels that each got.

#865 update(images): bump kernel-crawler image tag.
  images/update-kernels/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#866 update(config.yaml): protect libs `0.9.0` release branch
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#838 Bump prow from v20220901-5db9cf5fa2 to v20221007-08c3d7a2a6
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#870 update(images): bumped kernel-crawler image to 0.1.3.
  images/update-kernels/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#871 update(config.yaml): protect Falco 0.33.0 branch
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#872 Bump prow from v20221007-08c3d7a2a6 to v20221014-f54c8765a7
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#874 fix(config/org.yaml): GH username changed
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#873 update(on-registry-changed): set environment variables for updating t…
  images/build-plugins/on-registry-changed.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#876 update(config.yaml): protect v0.32 website snapshot branch
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#875 Drivers website
  config/clusters/ecr.tf
  config/jobs/build-prow-images/build-images.yaml
  config/jobs/build-prow-images/publish-images.yaml
  config/jobs/update-drivers-website/update-drivers-website.yaml
  images/update-drivers-website/Dockerfile
  images/update-drivers-website/Makefile
  images/update-drivers-website/entrypoint.sh
  images/update-drivers-website/index.html
  images/update-drivers-website/updateDriversWebsite.go
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#879 encode only a component
  images/update-drivers-website/index.html
Labels: lgtm, approved, size/XS, dco-signoff: yes

#880 update(config): renamed master to main in event-generator.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#826 new(config): added ubuntu azure, gke, gcp flavors jobs.
  config/jobs/build-drivers/build-new-ubuntu-azure.yaml
  config/jobs/build-drivers/build-new-ubuntu-gcp.yaml
  config/jobs/build-drivers/build-new-ubuntu-gke.yaml
  config/jobs/build-drivers/rebuild-all-ubuntu-azure.yaml
  config/jobs/build-drivers/rebuild-all-ubuntu-gcp.yaml
  config/jobs/build-drivers/rebuild-all-ubuntu-gke.yaml
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#868 update(images): bumped build-drivers driverkit to 0.10.2
  driverkit/utils/generate
  images/build-drivers/Dockerfile
Labels: size/M, lgtm, approved, dco-signoff: yes

#882 Bump prow from v20221014-f54c8765a7 to v20221021-f6c02074bb
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes
