Repository falcosecurity/test-infra, pull requests merged in 2022-09, with the labels that each got.

#825 fix(images/update-maintainers): correct `GH_REPO_BRANCH` default
  images/update-maintainers/entrypoint.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#827 fix(config/org.yaml): remove empty fields
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#828 fix(config/org.yaml): at least one merge strategy is needed
  config/org.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#807 Bump prow from v20220812-9414716697 to v20220901-5db9cf5fa2
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#829 update(config/org.yaml): add jasondellaluce to github-maintainers team
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#830 update(config/org.yaml): add Andrea Terzolo as a Falco maintainer
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#831 Set correct `CONTRIBUTING.md` path for DCO plugin
  config/plugins.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#833 fix(images): fixed update_kernels image entrypoint paths.
  images/update-kernels/entrypoint.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#834 fix(config): update_kernels now uses `kernels` branch
  config/jobs/update-kernels/update-kernels.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#839 fix(config,images): fixed update-kernels entrypoint.
  config/jobs/update-kernels/update-kernels.yaml
  images/update-kernels/entrypoint.sh
Labels: lgtm, approved, dco-signoff: yes, size/S

#846 update(config.yaml): set some libs CI checks as required
  config/config.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#845 update(config): add loresuso to org members
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#847 update(config): update status check names
  config/config.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#850 fix(images): fixed update-kernels image entrypoint to fetch all branches before checking out `kernels`
  images/update-kernels/entrypoint.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#852 update(org.yalm): sync falcoctl owners
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#851 update(config): falcoctl branches
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#853 ci(update-kernels): increase verbosity
  images/update-kernels/entrypoint.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#858 fix(build-plugins/on-registry-changed.sh): correct checkout path
  images/build-plugins/on-registry-changed.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#849 adding new configuration files for amazonlinux2_5.4.209-116.367.amzn2
  driverkit/config/2.0.0+driver/aarch64/amazonlinux2_5.4.209-116.367.amzn2.aarch64_1.yaml
  driverkit/config/2.0.0+driver/x86_64/amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.yaml
  driverkit/config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.yaml
  driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes, ok-to-test

#861 cleanup(driverkit): dropped a rocky config whose name was wrong
  driverkit/config/2.0.0+driver/x86_64/rocky_4.18.0-348.12.2.el8_5.x86_64_1.yaml
  driverkit/config/39ae7d40496793cf3d3e7890c9bbdc202263836b/rocky_4.18.0-348.12.2.el8_5.x86_64_1.yaml
  driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/rocky_4.18.0-348.12.2.el8_5.x86_64_1.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#862 chore(config): change update-kernels job cron.
  config/jobs/update-kernels/update-kernels.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes
