Repository falcosecurity/test-infra, pull requests merged in 2022-05, with the labels that each got.

#677 Bump prow from v20220414-949f7bddd3 to v20220506-6d355b2d97
  config/config.yaml
  config/jobs/arm-build/arm-build.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#693 update: updated driverkit to 0.8.0.
  images/build-drivers/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#695 ci(circleci/terrascan): fix bin download url
  .circleci/config.yml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#694 update(persons): add Fred Araujo
  images/update-maintainers/persons.json
Labels: lgtm, approved, size/XS, dco-signoff: yes

#703 Add Secureworks to persons.json
  images/update-maintainers/persons.json
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#705 add ubuntu-generic_5.15.0-27-generic_28
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.15.0-27-generic_28.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.15.0-27-generic_28.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/ubuntu-generic_5.15.0-27-generic_28.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.15.0-27-generic_28.yaml
  driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/ubuntu-generic_5.15.0-27-generic_28.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes, ok-to-test

#708 update(persons): add Teryl Taylor
  images/update-maintainers/persons.json
Labels: lgtm, approved, size/XS, dco-signoff: yes

#710 Add config for amazonlinux2_5.4.190-107.353
  driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.190-107.353.amzn2.x86_64_1.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.4.190-107.353.amzn2.x86_64_1.yaml
  driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.4.190-107.353.amzn2.x86_64_1.yaml
  driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.190-107.353.amzn2.x86_64_1.yaml
  driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.4.190-107.353.amzn2.x86_64_1.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes, ok-to-test
