Repository falcosecurity/test-infra, pull requests merged in 2022-06, with the labels that each got.

#712 chore(config/org.yaml): add dwindsor as driverkit maintainer
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#715 add Issif as member for website
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#716 fix(images/update-falco-k8s-manifests): correct target branch
  images/update-falco-k8s-manifests/entrypoint.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#718 ci: add missing update-dbg image build and push jobs
  config/jobs/build-prow-images/build-images.yaml
  config/jobs/build-prow-images/publish-images.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#719 fix(config): update required_status_checks for Falco
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#721 fix(config/jobs): correct repo and branch for update-falco-k8s-manifests
  config/jobs/update-falco-k8s-manifests/update-falco-k8s-manifests.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#723 update(images): updated prcreator images to golang 1.18.
  images/autobump/Dockerfile
  images/update-dbg/Dockerfile
  images/update-kernels/Dockerfile
Labels: lgtm, approved, dco-signoff: yes, size/S

#720 chore(config): dropped arm-build job as latest Falco does now support arm64
  config/clusters/ecr.tf
  config/jobs/arm-build/arm-build.yaml
  tools/create_ecr.sh
Labels: size/M, lgtm, approved, dco-signoff: yes

#725 cleanup(config): dropped reference to arm-build job.
  config/clusters/ecr-iam.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#726 fix(config): update-kernels should use main in place of master.
  config/jobs/update-kernels/update-kernels.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#728 fix(scripts): use single quotes to escape newline chars in "body" variable
  images/update-falco-k8s-manifests/entrypoint.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes, needs-ok-to-test

#729 fix(config): correct wrong team binding for the libs-sdk-go repo
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#730 fix(images): fix update-kernels image entrypoint python commands.
  images/update-kernels/entrypoint.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#731 fix(images): update-kernels requires setuptools.
  images/update-kernels/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#732 fix(images): update-kernels entrypoint should use main branch.
  images/update-kernels/entrypoint.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#724 20220610 - drivers for Ubuntu 20.04
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-100-generic_113.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-104-generic_118.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-105-generic_119.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-107-generic_121.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-109-generic_123.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-110-generic_124.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-113-generic_127.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-117-generic_132.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-91-generic_102.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-92-generic_103.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-94-generic_106.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-97-generic_110.yaml
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-99-generic_112.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes, ok-to-test

#735 fix(driverkit-config): Fix configuration of driverkit for ubuntu driver
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-117-generic_132.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#740 Add configs for amazonlinux2_5.4.196-108.356.amzn2.x86_64_1
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.4.196-108.356.amzn2.x86_64_1.yaml
  driverkit/config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_5.4.196-108.356.amzn2.x86_64_1.yaml
  driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.4.196-108.356.amzn2.x86_64_1.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S, ok-to-test

#741 update(config): update falco-maintainers team
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#742 Adding new driverkit for amazonlinux2_4.14.275-207.503.amzn2.x86_64_1
  driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_4.14.275-207.503.amzn2.x86_64_1.yaml
  driverkit/config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_4.14.275-207.503.amzn2.x86_64_1.yaml
  driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_4.14.275-207.503.amzn2.x86_64_1.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S, ok-to-test
