Repository falcosecurity/test-infra, pull requests merged in 2022-07, with the labels that each got.

#749 chore(driverkit): skip arm64 config generation for old tree, as arm64 was unsupported
  driverkit/utils/generate
Labels: lgtm, approved, dco-signoff: yes, size/S

#757 chore(configs): updated run-if-changed for dbg jobs splitted by major kernel version.
  config/jobs/build-drivers/build-new-centos.yaml
  config/jobs/build-drivers/build-new-ubuntu-aws.yaml
  config/jobs/build-drivers/build-new-ubuntu-generic.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#759 chore(config): run update-dbg job as soon as new kernel lists are merged in main in kernel-crawler repo
  config/jobs/update-dbg/update-dbg.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#748 chore(config): added tests-integration-arm64 to Falco required_status _checks
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#763 update(images/update-maintainers): update company affiliations in persons.json
  images/update-maintainers/persons.json
Labels: lgtm, approved, dco-signoff: yes, size/S

#762 update(config): enable milestone plugin on falcosecurity/libs
  config/plugins.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#765 update(config/org.yaml): add Molter73
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#767 update(persons): add Mauro Ezequiel Moltrasio
  images/update-maintainers/persons.json
Labels: lgtm, approved, size/XS, dco-signoff: yes

#769 update(config/org.yaml): archiving `template-repository` repo
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#770 fix(config/org.yaml): add missing maintainer to `kilt`
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#771 update(config): added fededp to driverkit and event-generator maintainers lists
  config/org.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#773 update(config/org.yaml): archiving `katacoda-scenarios`
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#750 cleanup(config,images): dropped build-libs images
  config/clusters/ecr-iam.tf
  config/clusters/ecr.tf
  config/jobs/build-libs/build-libs.yaml
  config/jobs/build-prow-images/build-images.yaml
  config/jobs/build-prow-images/publish-images.yaml
  tools/create_ecr.sh
Labels: lgtm, approved, dco-signoff: yes, size/L

#774 cleanup(images): dropped build-libs images.
  images/build-libs/Dockerfile
  images/build-libs/Makefile
  images/build-libs/build.sh
Labels: lgtm, approved, dco-signoff: yes, size/L

#775 update(config/org.yaml): invite `darryk10` to the org
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#776 bulk update and cleanup of config/org.yaml
  config/org.yaml
Labels: lgtm, approved, dco-signoff: yes, size/XL

#781 docs: add LICENSE
  LICENSE
Labels: lgtm, approved, dco-signoff: yes, size/L

#784 update(config/org): archiving unmaintained repositories
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#779 chore: config for amazonlinux2_5.4.201-111.359
  driverkit/config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_5.4.201-111.359.amzn2.x86_64_1.yaml
  driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.4.201-111.359.amzn2.x86_64_1.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S, ok-to-test
