Repository falcosecurity/test-infra, pull requests merged in 2023-09, with the labels that each got.

#1224 Update (org.yaml): add rohith as a member
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, needs-ok-to-test

#1225 new(config): set up falco-playground repo.
  config/config.yaml
  config/org.yaml
  config/plugins.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1228 update: set release branch 0.13.x as protected
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1231 update(config): set some libs CI tests as required
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1233 new(tf): add Falco ECR public repositories
  config/distribution/containers.tf
Labels: lgtm, approved, dco-signoff: yes, size/L

#1237 new(tf): add configuration for falcosidekick-ui
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#1206 Update Prow to v20230901-e9e5d470a5
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1247 chore(config): protect v0.35 branch on falco-website
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1248 new(config): setup dbg-go repo.
  config/config.yaml
  config/org.yaml
  config/plugins.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1249 chore(config): protect dbg-go main branch.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1250 update(distribution): vendor s3-bucket-listing
  config/distribution/distribution.tf
  config/distribution/files/index.html
  config/distribution/files/s3-list.js
Labels: lgtm, approved, dco-signoff: yes, size/XL
