Repository falcosecurity/test-infra, pull requests merged in 2023-05, with the labels that each got.

#1108 cleanup(config/prow): removed unused build-plugins s3 serviceaccount
  config/prow/build-plugins-serviceaccount.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1121 new(iam): add Falco CloudFront access
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#1124 fix(iam): correct falco repository name
  config/clusters/iam.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1125 fix(iam): add falco-driver-loader and falco-no-driver ECR
  config/clusters/iam.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1120 Add postsubmit job to sync Peribolos GitHub Teams from OWNERS
  config/jobs/update-github-teams/peribolos-syncer.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L

#1127 update(config): remove a no more required job for libs
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1136 update(config/jobs/build-drivers): added tolerations to build-drivers jobs configurations.
  config/jobs/build-drivers/build-new-almalinux.yaml
  config/jobs/build-drivers/build-new-amazonlinux.yaml
  config/jobs/build-drivers/build-new-bottlerocket.yaml
  config/jobs/build-drivers/build-new-centos.yaml
  config/jobs/build-drivers/build-new-debian.yaml
  config/jobs/build-drivers/build-new-fedora.yaml
  config/jobs/build-drivers/build-new-minikube.yaml
  config/jobs/build-drivers/build-new-ubuntu-aws.yaml
  config/jobs/build-drivers/build-new-ubuntu-azure.yaml
  config/jobs/build-drivers/build-new-ubuntu-gcp.yaml
  config/jobs/build-drivers/build-new-ubuntu-generic.yaml
  config/jobs/build-drivers/build-new-ubuntu-gke.yaml
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#1137 update(config/jobs/build-drivers): updated arm jobs tolerations for single AZ taint.
  config/jobs/build-drivers/build-new-almalinux.yaml
  config/jobs/build-drivers/build-new-amazonlinux.yaml
  config/jobs/build-drivers/build-new-bottlerocket.yaml
  config/jobs/build-drivers/build-new-centos.yaml
  config/jobs/build-drivers/build-new-debian.yaml
  config/jobs/build-drivers/build-new-fedora.yaml
  config/jobs/build-drivers/build-new-minikube.yaml
  config/jobs/build-drivers/build-new-ubuntu-aws.yaml
  config/jobs/build-drivers/build-new-ubuntu-azure.yaml
  config/jobs/build-drivers/build-new-ubuntu-gcp.yaml
  config/jobs/build-drivers/build-new-ubuntu-generic.yaml
  config/jobs/build-drivers/build-new-ubuntu-gke.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L

#1139 fix(tools/deploy_terraform.sh): update bin download to current tf reqs
  tools/deploy_terraform.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1140 update(iam): allow dev role for prerelease tags
  config/clusters/iam.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1144 fix(config/prow/arc): add selection and tolerations for jobs on arm nodes
  config/prow/arc/arm-runner.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1146 perf(config/clusters): tune node groups max horizontal capacity
  config/clusters/prow.tfvars
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1149 fix(config/jobs/autobump/autobump.yaml): removed unused ssh key volume mount.
  config/jobs/autobump/autobump.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1154 chore(config): fixed some validate-new-drivers job names.
  config/jobs/build-drivers/build-new-almalinux.yaml
  config/jobs/build-drivers/build-new-debian.yaml
  config/jobs/build-drivers/build-new-fedora.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1160 update(images): bumped driverkit to latest 0.13.0.
  images/build-drivers/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1099 new(config): added amazonlinux2023 build-drivers jobs.
  config/jobs/build-drivers/build-new-amazonlinux.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L

#1162 fix(jobs/build-drivers/al2023): add missing node tolerations
  config/jobs/build-drivers/build-new-amazonlinux.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1129 new(config): added talos build-drivers jobs.
  config/jobs/build-drivers/build-new-talos.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L

#1165 refactor(config/clusters): move jobs on arm to different subnet
  config/clusters/eks.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes
