Repository falcosecurity/test-infra, pull requests merged in 2023-07, with the labels that each got.

#1132 cleanup(images/autobump): old autobump image removal.
  images/autobump/Dockerfile
  images/autobump/Makefile
  images/autobump/autobump.sh
  images/autobump/bump.sh
Labels: lgtm, approved, dco-signoff: yes, size/XL

#1133 cleanup(config/clusters/ecr.tf): autobump ecr force delete.
  config/clusters/ecr.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1194 cleanup(config/clusters/ecr.tf): removed old autobumper ecr resource.
  config/clusters/TERRAFORM.md
  config/clusters/ecr-iam.tf
  config/clusters/ecr.tf
  docs/update-cluster.md
  tools/create_ecr.sh
Labels: lgtm, approved, dco-signoff: yes, size/S

#1198 update(images): bumped driverkit to 0.14.0.
  images/build-drivers/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1192 fix(config): fixed a couple of validate-ubuntu jobs names.
  config/jobs/build-drivers/build-new-ubuntu-generic.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1200 new(config): add kernel-testing repo.
  config/config.yaml
  config/org.yaml
  config/plugins.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1202 update(config): protect libs 0.12.x
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes
