Repository falcosecurity/test-infra, pull requests merged in 2023-12, with the labels that each got.

#1309 update(org): add myself as a falco-website member
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1316 cleanup(config,tools): drop ARC.
  config/prow/arc/arm-runner.yaml
  tools/deploy_prow.sh
Labels: size/M, lgtm, approved, dco-signoff: yes

#1319 new(config): updated libs required status checks.
  config/config.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1322 update(config): archiving `kilt`
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1329 chore(config): updated driverkit required status checks.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1331 update(config): add falcosecurity/cncf-green-review-testing repo
  config/config.yaml
  config/org.yaml
  config/plugins.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1333 Protect branch 0.14.x
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1334 update(images): bumped dbg-go to latest release.
  images/build-drivers/Dockerfile
  images/update-dbg/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1336 update(config): bumped event-generator required status checks.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes
