Repository falcosecurity/test-infra, pull requests merged in 2023-04, with the labels that each got.

#1047 update(config): add `manifests-validation` to required status checks for test-infra repo
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1076 adding EXONER4TED to kernel-crawler org
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1079 fix(tools): force server-side flag when applying ARC resources.
  tools/deploy_prow.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1081 fix(prow): do not fail if the secret already exists
  tools/deploy_prow.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1013 new(ci): added update-drivers-website gha.
  .github/workflows/update-drivers-website.yml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1083 chore(ci): added permissions to workflow
  .github/workflows/update-drivers-website.yml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1084 cleanup(config/jobs): remove update-drivers-website build/publish image trigger
  config/jobs/build-prow-images/build-images.yaml
  config/jobs/build-prow-images/publish-images.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1087 cleanup(config/clusters/ecr.tf): removed update-drivers-website job ecr resource
  config/clusters/ecr.tf
Labels: lgtm, approved, dco-signoff: yes, size/S

#1005 update(config/clusters): ec2 cluster scale-out
  config/clusters/prow.tfvars
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#1091 cleanup(config/jobs/build-plugin-sdk-go): build-plugin-sdk-go ci job removal.
  config/jobs/build-plugin-sdk-go/build-plugin-sdk-go.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1092 update(config/config.yaml): added run-tests ci job to plugin-sdk-go repo.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1094 chore(config/clusters/prow.tfvars): increased asg capacities.
  config/clusters/prow.tfvars
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1096 update(config/jobs/build-drivers): added jobs for ubuntu 6.x and centos 6.x kernel versions
  config/jobs/build-drivers/build-new-centos.yaml
  config/jobs/build-drivers/build-new-ubuntu-aws.yaml
  config/jobs/build-drivers/build-new-ubuntu-azure.yaml
  config/jobs/build-drivers/build-new-ubuntu-gcp.yaml
  config/jobs/build-drivers/build-new-ubuntu-generic.yaml
  config/jobs/build-drivers/build-new-ubuntu-gke.yaml
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#1098 new(config/clusters/iam.tf): added policies for S3 access plugins repo GHA
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#1103 cleanup(config/jobs/build-plugins/build-plugins.yaml): removed build-plugins jobs configs
  config/jobs/build-plugins/build-plugins.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L

#1105 cleanup(config/clusters/iam.tf): removed policy for build-plugins job S3 access.
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#1102 new(config): added iam s3 access roles for Falco (dev and release).
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#1113 new(iam): add Falco ECR access
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes
