Repository falcosecurity/test-infra, pull requests merged in 2023-03, with the labels that each got.

#1014 Create build-new-fedora.yaml
  config/jobs/build-drivers/build-new-fedora.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes, ok-to-test

#1016 Bump prow from v20230224-60dadd267c to v20230303-d699058042
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1017 new(tf): allow the falcosidekick repository to push to its own ECR repo
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#1023 update(images): update driverkit to latest version.
  images/build-drivers/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1022 Bump prow from v20230303-d699058042 to v20230309-adf0d41516
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1025 feat(infra/acm): add certificate for monitoring.prow.falco.org
  config/clusters/kubernetes.tf
  config/clusters/monitoring.tf
Labels: lgtm, approved, dco-signoff: yes, size/S

#1026 chore(config/prow/monitoring: temporarily expose grafana http only
  config/prow/monitoring/grafana_expose.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1030 fix(config/prow/monitoring): set existent standard storageclass
  config/prow/monitoring/grafana_ingress.yaml
  config/prow/monitoring/prow_alertmanager.yaml
  config/prow/monitoring/prow_prometheus.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1028 feat(config/prow): expose metrics ports for prometheus servicemonitors
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1038 fix(config/prow): add kube-state-metrics deployment
  config/prow/kube-state-metrics_deployment.yaml
  config/prow/kube-state-metrics_rbac.yaml
  config/prow/kube-state-metrics_service.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L

#1043 new(ci): added manifests validation ci
  .github/workflows/validate_manifests.yml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1048 Bump prow from v20230309-adf0d41516 to v20230315-6d54c174f4
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1052 fix(ci): properly install `make`
  .circleci/config.yml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1053 fix(config/prow/monitoring/grafana): remove not reproducible metadata
  config/prow/monitoring/grafana_ingress.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1054 ci(circle/config): add golang package to circleci job
  .circleci/config.yml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1056 fix(config/prow): connect servicemonitor to new node-exporter
  config/prow/monitoring/node-exporter_servicemonitor.yaml
  config/prow/node-exporter.yaml
  config/prow/node-exporter_deployment.yaml
  config/prow/node-exporter_rbac.yaml
  config/prow/node-exporter_service.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L

#1059 fix(config/prow/monitoring/nodes): mount missing grafana dashboard configmaps
  config/prow/monitoring/grafana_deployment.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1061 chore(prow/monitoring): remove duplicated manifests
  config/prow/monitoring/node-exporter_servicemonitors.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1062 update(config/prow/monitoring): bumped grafana version
  config/prow/monitoring/grafana_deployment.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1065 feat(prow/monitoring): expose grafana via https and wellknown hostname
  config/prow/monitoring/grafana_ingress.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1066 Fix/add missing nodes prometheusrules
  config/prow/monitoring/mixins/Makefile
  config/prow/monitoring/mixins/vendor/github.com/prometheus/node_exporter/docs/node-mixin/Makefile
  config/prow/monitoring/mixins/vendor/github.com/prometheus/node_exporter/docs/node-mixin/prometheusrule.jsonnet
Labels: size/M, lgtm, approved, dco-signoff: yes

#1067 chore(config/org.yaml): add myself (Lowaiz) as driverkit maintainer
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#1073 revert: "Bump prow from v20230315-6d54c174f4 to v20230324-8697ff4d24"
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes
