Repository falcosecurity/test-infra, pull requests merged in 2023-01, with the labels that each got.

#940 Bump prow from v20221220-5c7fbe528a to v20230106-0de7d15106
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#939 new(org): add LucaGuerra as admin
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#942 chore(config/clusters/eks): add fededp as prow eks admin user
  config/clusters/eks_variables.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#944 update(images): trigger publish for update-rules-index
  images/update-rules-index/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#945 chore(config): set release/0.10.x as protected branch.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#946 fix(update-rules-index): add OCI_REPO_PREFIX
  images/update-rules-index/on-registry-changed.sh
Labels: lgtm, approved, size/XS, dco-signoff: yes

#947 new(tf): add S3 permissions for GitHub Actions on rules repo
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#948 fix(tf): temporarily revert PR#947
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#951 fix(config/jobs/build-drivers): corrected nodeSelector position
  config/jobs/build-drivers/build-new-amazonlinux.yaml
  config/jobs/build-drivers/build-new-bottlerocket.yaml
  config/jobs/build-drivers/build-new-centos.yaml
  config/jobs/build-drivers/build-new-debian.yaml
  config/jobs/build-drivers/build-new-minikube.yaml
  config/jobs/build-drivers/build-new-ubuntu-aws.yaml
  config/jobs/build-drivers/build-new-ubuntu-azure.yaml
  config/jobs/build-drivers/build-new-ubuntu-gcp.yaml
  config/jobs/build-drivers/build-new-ubuntu-generic.yaml
  config/jobs/build-drivers/build-new-ubuntu-gke.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L, ok-to-test

#952 Bump prow from v20230106-0de7d15106 to v20230113-8f2ffbe0d4
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#930 cleanup(config): dropped rebuild-all-drivers jobs.
  config/jobs/build-drivers/rebuild-all-amazonlinux.yaml
  config/jobs/build-drivers/rebuild-all-bottlerocket.yaml
  config/jobs/build-drivers/rebuild-all-centos.yaml
  config/jobs/build-drivers/rebuild-all-debian.yaml
  config/jobs/build-drivers/rebuild-all-minikube.yaml
  config/jobs/build-drivers/rebuild-all-ubuntu-aws.yaml
  config/jobs/build-drivers/rebuild-all-ubuntu-azure.yaml
  config/jobs/build-drivers/rebuild-all-ubuntu-gcp.yaml
  config/jobs/build-drivers/rebuild-all-ubuntu-generic.yaml
  config/jobs/build-drivers/rebuild-all-ubuntu-gke.yaml
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#954 fix(config): fixed falcosecurity/rules members.
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#955 update(prow): retire 1password, use secret env variables
  Makefile
  docs/one-password.md
  tools/1password.sh
  tools/deploy_prow.sh
Labels: lgtm, approved, dco-signoff: yes, size/L

#956 new(eks): add luca.guerra to the EKS test-infra cluster
  config/clusters/eks_variables.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#957 update(config): updated client-go required status check.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#960 update(config): updated falco-exporter required status checks.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#958 update(config): added event-generator required status checks.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#959 update(config): change a required libs job
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#963 update(org.yaml): add jasondellaluce to libs-maintainers
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#964 new(tf): add S3 permissions for GitHub Actions on rules repo (take 2)
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#916 new(driverkit): configs regenerated after each dbg update
  driverkit/Makefile
  driverkit/README.md
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#966 fix(driverkit): fixed dbg cleanup.
  driverkit/Makefile
Labels: lgtm, approved, dco-signoff: yes, size/S

#968 fix(dbg): remove cleanup targets overlap
  driverkit/Makefile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#971 update(config): initial rules prow configuration
  config/plugins.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, needs-ok-to-test

#970 Bump prow from v20230113-8f2ffbe0d4 to v20230120-5ca317e736
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#974 Bump prow from v20230120-5ca317e736 to v20230127-c2d8597baa
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes
