Repository falcosecurity/test-infra, pull requests merged in 2023-02, with the labels that each got.

#977 cleanup(prow): removed build/publish update-syscalls jobs
  config/clusters/ecr.tf
  config/jobs/build-prow-images/build-images.yaml
  config/jobs/build-prow-images/publish-images.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes, ok-to-test

#978 chore(config/clusters/ecr): allow force delete on update-syscalls repo
  config/clusters/ecr.tf
Labels: lgtm, approved, dco-signoff: yes, size/S

#975 update(images): updated driverkit to v0.11.1.
  images/build-drivers/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#980 fix(config): update-dbg job should only run when a `list.json` file is touched
  config/jobs/update-dbg/update-dbg.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#982 update: adding vjjmiras to the members section of the org.yaml file
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#983 cleanup(prow): removed build/publish update-kernels job
  config/jobs/build-prow-images/build-images.yaml
  config/jobs/build-prow-images/publish-images.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes, ok-to-test

#987 cleanup(config/clusters/ecr): force delete on update-kernels repo
  config/clusters/ecr.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#988 cleanup(config/clusters/ecr): removed update-kernels from ecr.
  config/clusters/ecr.tf
Labels: lgtm, approved, dco-signoff: yes, size/S, ok-to-test

#989 chore(config/clusters/ecr-iam): removed update-kernels resource.
  config/clusters/ecr-iam.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#990 update: add incertum to libs-maintainer
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#991 update(config): protect Falco release branch 0.34.0
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#984 Bump prow from v20230127-c2d8597baa to v20230202-2cc77b11a8
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#992 update(config): remove required arm64 jobs
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#993 update(config): protect falco-website branch v0.33
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#994 Add flycheck-falco-rules to test-infra
  config/config.yaml
  config/org.yaml
  config/plugins.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#995 fix(config): add incertum to the `core-maintainers` team
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#997 fix(config/jobs): fixed amazonlinux2 aarch64 build-drivers job.
  config/jobs/build-drivers/build-new-amazonlinux.yaml
  config/jobs/build-drivers/build-new-bottlerocket.yaml
  config/jobs/build-drivers/build-new-centos.yaml
  config/jobs/build-drivers/build-new-ubuntu-aws.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L

#1002 fix(config/plugins.yaml): add missing milestone maintainers team setting
  config/plugins.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1006 update k8s registry domain
  config/prow/cluster-autoscaler.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1008 update(config): protect falco release branch
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1009 Bump prow from v20230209-f319bbff04 to v20230215-1f9eebbd96
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1012 Bump prow from v20230215-1f9eebbd96 to v20230224-60dadd267c
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes
