Repository falcosecurity/test-infra, pull requests merged in 2024-03, with the labels that each got.

#1402 update(images): bumped dbg-go to latest release.
  images/build-drivers/Dockerfile
  images/update-dbg/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1412 new(config): create distribution for play.falco.org
  config/distribution/playground.tf
  config/distribution/variables.tf
Labels: lgtm, approved, dco-signoff: yes, size/L

#1413 new(config): add S3 and CloudFront permissions for falco-playground repo
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#1415 fix(tf): add S3 list access to Falco Playground
  config/clusters/iam.tf
Labels: lgtm, approved, dco-signoff: yes, size/S

#1419 chore: protect libs release branch 0.15.x
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1425 feat(iam): add infra reader role for gha oidc
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#1426 chore(k8s): add role binding to read aws-auth configmap
  config/prow/aws-auth-config-rbac.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1428 update(org.yaml): adding sboschman to falcosecurity/plugins/k8saudit-gke
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1433 fix(clusters/iam): set correct oidc subject for prs
  config/clusters/iam.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes
