Repository falcosecurity/test-infra, pull requests merged in 2024-11, with the labels that each got.

#1680 update(docs): add myself as plugins maintainer
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1666 update(docs): add LucaGuerra as owner
  OWNERS
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1684 update(alb-controller): introduce argocd application for alb-controller
  config/applications/alb-controller.yaml
  config/prow/alb_controller.yaml
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#1687 update(falco): bump chart version to 4.14.0
  config/applications/falco.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1698 Revert "chore: remove zig jobs from required ones"
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1695 update(config): add falco-actions
  config/config.yaml
  config/org.yaml
  config/plugins.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1699 add config for falco-talon
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1701 update(images): bump dbg-go to v0.16.0.
  images/build-drivers/Dockerfile
  images/update-dbg/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1703 new(app): prometheus operator crds
  config/applications/prometheus-operator-crds.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1704 update kube-prometheus-stack application
  config/applications/kube-stack-prometheus.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1706 update(falco): bump falco chart to 4.15.0
  config/applications/falco.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1708 chore(config): protect libs release/0.19.x branch.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes
