Repository falcosecurity/test-infra, pull requests merged in 2024-07, with the labels that each got.

#1545 update(config/org.yaml): invite sgaist to falcosecurity GH org
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1546 update(config/org.yaml): add sgaist to `falco` maintainers team
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1551 update(prow): update prowjob crd to the latest version
  config/prow/prowjob-crd/prowjob_custromresourcedefinition.yaml
  config/prow/prowjob_custromresourcedefinition.yaml
  tools/deploy_prow.sh
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#1552 fix(config/plugins): remove duplicated entries in approve section
  config/plugins.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1239 Update Prow to v20240403-f1101a8b4e
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes, lifecycle/stale

#1553 fix(config/prow):"add "get" permission to prow-controller for pod reources
  config/prow/prow-controller-manager.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1554 update(config/prow): upgrade ebs-csi-driver to version 1.32
  config/prow/ebs-csi-driver/ebs-csi-controller.yaml
  tools/deploy_prow.sh
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#1556 update(cluster/aws-lb): upgrade aws-load-balancer to version 2.4.7
  config/clusters/iam.tf
  config/prow/alb_controller.yaml
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#1557 fix(prow/aws-load-balancer): use correct iam role
  config/prow/alb_controller.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1558 new(config/prow): add pod-identity-webhook
  config/prow/pod-identity-webhook/auth.yaml
  config/prow/pod-identity-webhook/deployment-base.yaml
  config/prow/pod-identity-webhook/mutatingwebhook.yaml
  config/prow/pod-identity-webhook/namespace.yaml
  config/prow/pod-identity-webhook/service.yaml
  tools/deploy_prow.sh
Labels: lgtm, approved, dco-signoff: yes, size/L

#1559 update(config/prow): migrate ingress to networking.k8s.io/v1 api version
  config/prow/alb_ingress.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1560 update(cluster): bump k8s version to 1.24
  config/clusters/eks_variables.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1561 update(cluster): bump k8s version to 1.22
  config/clusters/eks_variables.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1562 update(config/prow): run infra pods only in x86 nodes
  config/prow/alb_controller.yaml
  config/prow/ebs-csi-driver/ebs-csi-controller.yaml
  config/prow/pod-identity-webhook/deployment-base.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1563 cleanup(prow/plugins): remove saymyname plugin
  config/plugins.yaml
  config/prow/saymyname.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1564 update(cluster): bump k8s version to 1.23
  config/clusters/eks_variables.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1565 update(cluster): bump k8s version to 1.24
  config/clusters/eks_variables.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1566 update(config/cluster): adjust iam role for autoscaler
  config/clusters/iam.tf
Labels: lgtm, approved, dco-signoff: yes, size/S

#1567 Kcl/update autoscale iam role
  config/clusters/iam.tf
Labels: lgtm, approved, dco-signoff: yes, size/S

#1568 update(config/prow): bump cluster-autoscaler to version 1.30.1
  config/prow/cluster-autoscaler.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1570 update(aws-load-balancer-controller): update iam policy
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#1569 update(cluster): bump k8s version to 1.25
  config/clusters/eks_variables.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1573 Kcl/bump cert manager v1.15.1
  config/prow/cert-manager.yaml
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#1572 update(cluster): bump k8s version to 1.26
  config/clusters/eks_variables.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1576 update(cluster): bump k8s version to 1.28
  config/clusters/eks_variables.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1578 update(kube-state-metrics): adjust serviceMonitor
  config/prow/monitoring/kube-state-metrics_servicemonitors.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1579 update(cluster): bump k8s version to 1.29
  config/clusters/eks_variables.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1580 update(cluster): bump k8s version to 1.30
  config/clusters/eks_variables.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1581 new(ebs-csi-controller): ad-hoc iam role for ebs-csi-controller
  config/clusters/iam.tf
  config/prow/ebs-csi-driver/ebs-csi-controller.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L

#1586 fix(config/autobumper): fixed autobumper config adding `consistentImageExceptions`
  config/autobump-config/prow-autobump-config.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1587 Update Prow to v20240723-dbbd2d86b
  config/config.yaml
  config/jobs/branchprotector/branchprotector.yaml
  config/jobs/check-prow-config/check-prow-config.yaml
  config/jobs/lifecycle-bot/periodic-close.yaml
  config/jobs/lifecycle-bot/periodic-rotten.yaml
  config/jobs/lifecycle-bot/periodic-stale.yaml
  config/jobs/peribolos/peribolos.yaml
  config/prow/crier.yaml
  config/prow/deck.yaml
  config/prow/ghproxy.yaml
  config/prow/hook.yaml
  config/prow/horologium.yaml
  config/prow/needs-rebase.yaml
  config/prow/prow-controller-manager.yaml
  config/prow/sinker.yaml
  config/prow/statusreconciler.yaml
  config/prow/tide.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1592 update(images): bumped dbg-go to 0.14.0.
  images/build-drivers/Dockerfile
  images/update-dbg/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1594 update(config/org.yaml): add loresuso to falcoctl and core maintainers
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes
