Repository falcosecurity/test-infra, pull requests merged in 2024-10, with the labels that each got.

#1640 update(config): add falco-talon
  config/config.yaml
  config/org.yaml
  config/plugins.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L

#1659 chore(config): add back zig build to required checks on libs.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1661 update(config/org.yaml): add mrgian
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1662 update(config): add plugin-sdk-rs
  config/config.yaml
  config/org.yaml
  config/plugins.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L

#1671 new(tools): introduce argocd to handle applications' lifecycle
  .github/workflows/argocd.yml
  tools/deploy_argocd.sh
Labels: size/M, lgtm, approved, dco-signoff: yes

#1672 temporarily disable required arm64 tests
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1674 new(application): add falco
  config/applications/falco.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L
