Repository falcosecurity/test-infra, pull requests merged in 2024-04, with the labels that each got.

#1436 update(org.yaml): add alacuku to falcoctl, charts, and core maintainers
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1440 fix(config/jobs/update-github-teams): set correct trigger branch
  config/jobs/update-github-teams/peribolos-syncer-client-go.yaml
  config/jobs/update-github-teams/peribolos-syncer-driverkit.yaml
  config/jobs/update-github-teams/peribolos-syncer-falco-website.yaml
  config/jobs/update-github-teams/peribolos-syncer-falco.yaml
  config/jobs/update-github-teams/peribolos-syncer-falcosidekick-ui.yaml
  config/jobs/update-github-teams/peribolos-syncer-falcosidekick.yaml
  config/jobs/update-github-teams/peribolos-syncer-libs.yaml
  config/jobs/update-github-teams/peribolos-syncer-test-infra.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1444 chore(config/jobs): add test peribolos-syncer presubmit
  config/jobs/update-github-teams/peribolos-syncer-test-infra-pre-test.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1447 chore(config/jobs): set the test presubmit syncer job command
  config/jobs/update-github-teams/peribolos-syncer-test-infra-pre-test.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1448 chore(config/jobs): bump syncer for test job
  config/jobs/update-github-teams/peribolos-syncer-test-infra-pre-test.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1449 chore(config/jobs): set branch for update-github-teams test job
  config/jobs/update-github-teams/peribolos-syncer-test-infra-pre-test.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1452 fix(config/jobs): add `command` to peribolos-syncer jobs.
  config/jobs/update-github-teams/peribolos-syncer-charts.yaml
  config/jobs/update-github-teams/peribolos-syncer-client-go.yaml
  config/jobs/update-github-teams/peribolos-syncer-cncf-green-review-testing.yaml
  config/jobs/update-github-teams/peribolos-syncer-community.yaml
  config/jobs/update-github-teams/peribolos-syncer-contrib.yaml
  config/jobs/update-github-teams/peribolos-syncer-dbg-go.yaml
  config/jobs/update-github-teams/peribolos-syncer-deploy-kubernetes.yaml
  config/jobs/update-github-teams/peribolos-syncer-driverkit.yaml
  config/jobs/update-github-teams/peribolos-syncer-event-generator.yaml
  config/jobs/update-github-teams/peribolos-syncer-evolution.yaml
  config/jobs/update-github-teams/peribolos-syncer-falco-aws-terraform.yaml
  config/jobs/update-github-teams/peribolos-syncer-falco-exporter.yaml
  config/jobs/update-github-teams/peribolos-syncer-falco-playground.yaml
  config/jobs/update-github-teams/peribolos-syncer-falco-website.yaml
  config/jobs/update-github-teams/peribolos-syncer-falco.yaml
  config/jobs/update-github-teams/peribolos-syncer-falcoctl.yaml
  config/jobs/update-github-teams/peribolos-syncer-falcosidekick-ui.yaml
  config/jobs/update-github-teams/peribolos-syncer-falcosidekick.yaml
  config/jobs/update-github-teams/peribolos-syncer-flycheck-falco-rules.yaml
  config/jobs/update-github-teams/peribolos-syncer-k8s-metacollector.yaml
  config/jobs/update-github-teams/peribolos-syncer-kernel-crawler.yaml
  config/jobs/update-github-teams/peribolos-syncer-kernel-testing.yaml
  config/jobs/update-github-teams/peribolos-syncer-libs-sdk-go.yaml
  config/jobs/update-github-teams/peribolos-syncer-libs.yaml
  config/jobs/update-github-teams/peribolos-syncer-peribolos-syncer.yaml
  config/jobs/update-github-teams/peribolos-syncer-pigeon.yaml
  config/jobs/update-github-teams/peribolos-syncer-plugin-sdk-cpp.yaml
  config/jobs/update-github-teams/peribolos-syncer-plugin-sdk-go.yaml
  config/jobs/update-github-teams/peribolos-syncer-plugins.yaml
  config/jobs/update-github-teams/peribolos-syncer-rules.yaml
  config/jobs/update-github-teams/peribolos-syncer-syscalls-bumper.yaml
  config/jobs/update-github-teams/peribolos-syncer-test-infra.yaml
  config/jobs/update-github-teams/peribolos-syncer-testing.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1455 update(config/jobs): bump peribolos-syncer to v0.2.2.
  config/jobs/update-github-teams/peribolos-syncer-charts.yaml
  config/jobs/update-github-teams/peribolos-syncer-client-go.yaml
  config/jobs/update-github-teams/peribolos-syncer-cncf-green-review-testing.yaml
  config/jobs/update-github-teams/peribolos-syncer-community.yaml
  config/jobs/update-github-teams/peribolos-syncer-contrib.yaml
  config/jobs/update-github-teams/peribolos-syncer-dbg-go.yaml
  config/jobs/update-github-teams/peribolos-syncer-deploy-kubernetes.yaml
  config/jobs/update-github-teams/peribolos-syncer-driverkit.yaml
  config/jobs/update-github-teams/peribolos-syncer-event-generator.yaml
  config/jobs/update-github-teams/peribolos-syncer-evolution.yaml
  config/jobs/update-github-teams/peribolos-syncer-falco-aws-terraform.yaml
  config/jobs/update-github-teams/peribolos-syncer-falco-exporter.yaml
  config/jobs/update-github-teams/peribolos-syncer-falco-playground.yaml
  config/jobs/update-github-teams/peribolos-syncer-falco-website.yaml
  config/jobs/update-github-teams/peribolos-syncer-falco.yaml
  config/jobs/update-github-teams/peribolos-syncer-falcoctl.yaml
  config/jobs/update-github-teams/peribolos-syncer-falcosidekick-ui.yaml
  config/jobs/update-github-teams/peribolos-syncer-falcosidekick.yaml
  config/jobs/update-github-teams/peribolos-syncer-flycheck-falco-rules.yaml
  config/jobs/update-github-teams/peribolos-syncer-k8s-metacollector.yaml
  config/jobs/update-github-teams/peribolos-syncer-kernel-crawler.yaml
  config/jobs/update-github-teams/peribolos-syncer-kernel-testing.yaml
  config/jobs/update-github-teams/peribolos-syncer-libs-sdk-go.yaml
  config/jobs/update-github-teams/peribolos-syncer-libs.yaml
  config/jobs/update-github-teams/peribolos-syncer-peribolos-syncer.yaml
  config/jobs/update-github-teams/peribolos-syncer-pigeon.yaml
  config/jobs/update-github-teams/peribolos-syncer-plugin-sdk-cpp.yaml
  config/jobs/update-github-teams/peribolos-syncer-plugin-sdk-go.yaml
  config/jobs/update-github-teams/peribolos-syncer-plugins.yaml
  config/jobs/update-github-teams/peribolos-syncer-rules.yaml
  config/jobs/update-github-teams/peribolos-syncer-syscalls-bumper.yaml
  config/jobs/update-github-teams/peribolos-syncer-test-infra.yaml
  config/jobs/update-github-teams/peribolos-syncer-testing.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1473 chore(config): protect release/0.16.x branch on libs.
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1474 update(config): let FedeDP become an admin on the falcosecurity.
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes
