Repository falcosecurity/test-infra, pull requests merged in 2024-02, with the labels that each got.

#1372 update(config): remove test-dev-packages (static) requirement
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1381 update(config): temporarily remove required from asan build
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1159 update(config): added a new iam role for test-infra master CI (deploy terraform and prow)
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#1389 fix(tf): reduce falcoctl about field length
  config/distribution/containers.tf
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1388 new(tf): add aws iam role for falcoctl
  config/clusters/iam.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#1390 new(tf): add EKS permissions for GitHub Actions
  config/clusters/eks.tf
  config/clusters/eks_variables.tf
Labels: lgtm, approved, dco-signoff: yes, size/S

#1391 fix(ci): deploy prow still needs iam access.
  .github/workflows/master.yml
Labels: lgtm, approved, dco-signoff: yes, size/S

#1392 update(config): remove CircleCI
  .circleci/config.yml
  config/clusters/eks_variables.tf
Labels: size/M, lgtm, approved, dco-signoff: yes

#1394 update(config): update falcosecurity/libs sanitizer required checks
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes
