Repository falcosecurity/test-infra, pull requests merged in 2025-03, with the labels that each got.

#1788 update(config): add myself to `org.yaml` members
  config/org.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes, ok-to-test

#1796 fix(images/build-plugins): fix pr-creator
  images/build-plugins/Dockerfile
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1799 update(config/jobs): make `build-plugins.yaml` run on plugin release too
  config/jobs/build-plugins/build-plugins.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#1803 vote: docs(OWNERS): add alacuku (Aldo Lacuku) to approvers
  OWNERS
Labels: lgtm, approved, size/XS, dco-signoff: yes

#1810 fix(config): fix falco-operator repo name
  config/config.yaml
Labels: lgtm, approved, size/XS, dco-signoff: yes
